In [2]:
import pandas as pd

In [3]:

min_list=[]
max_list=[]
for i in range(1, 12+1):
    dfSensor = pd.read_excel('SensorsData.xlsx', sheet_name=f'Sheet{i}', usecols=[0, 1])
    dfSensor.rename(columns={"timestamp": "datetime", "sm": "sm_value"}, inplace=True)
    dfSensor["datetime"] = pd.to_datetime(dfSensor["datetime"])
    min_list.append(dfSensor["datetime"].min())
    max_list.append(dfSensor["datetime"].max())
print(f"Min: {min_list}")
print(f"Max: {max_list}")
max_abs=min(max_list)
min_abs=max(min_list)
print(min_abs)
print(max_abs)
full_index = pd.date_range(min_abs, max_abs, freq="h")

Min: [Timestamp('2024-12-12 12:00:00'), Timestamp('2024-12-12 12:00:00'), Timestamp('2024-12-12 12:00:00'), Timestamp('2024-12-12 12:00:00'), Timestamp('2024-12-12 12:00:00'), Timestamp('2024-12-12 12:00:00'), Timestamp('2024-12-12 12:00:00'), Timestamp('2024-12-12 12:00:00'), Timestamp('2024-12-12 12:00:00'), Timestamp('2024-12-12 12:00:00'), Timestamp('2024-12-12 12:00:00'), Timestamp('2024-12-12 12:00:00')]
Max: [Timestamp('2025-05-15 13:00:00'), Timestamp('2025-05-15 13:00:00'), Timestamp('2025-05-15 13:00:00'), Timestamp('2025-05-15 13:00:00'), Timestamp('2025-05-15 13:00:00'), Timestamp('2025-05-15 07:00:00'), Timestamp('2025-05-13 00:00:00'), Timestamp('2025-05-13 04:00:00'), Timestamp('2025-05-15 11:00:00'), Timestamp('2025-05-12 22:00:00'), Timestamp('2025-05-13 05:00:00'), Timestamp('2025-05-12 23:00:00')]
2024-12-12 12:00:00
2025-05-12 22:00:00

In [4]:
full_index

DatetimeIndex(['2024-12-12 12:00:00', '2024-12-12 13:00:00',
               '2024-12-12 14:00:00', '2024-12-12 15:00:00',
               '2024-12-12 16:00:00', '2024-12-12 17:00:00',
               '2024-12-12 18:00:00', '2024-12-12 19:00:00',
               '2024-12-12 20:00:00', '2024-12-12 21:00:00',
               ...
               '2025-05-12 13:00:00', '2025-05-12 14:00:00',
               '2025-05-12 15:00:00', '2025-05-12 16:00:00',
               '2025-05-12 17:00:00', '2025-05-12 18:00:00',
               '2025-05-12 19:00:00', '2025-05-12 20:00:00',
               '2025-05-12 21:00:00', '2025-05-12 22:00:00'],
              dtype='datetime64[ns]', length=3635, freq='h')

In [6]:
sensors = {}
for i in range(1, 12+1):
    dfSensor = pd.read_excel('SensorsData.xlsx', sheet_name=f'Sheet{i}', usecols=[0, 1])
    dfSensor.rename(columns={"timestamp": "datetime", "sm": "sm_value"}, inplace=True)
    dfSensor["datetime"] = pd.to_datetime(dfSensor["datetime"])
    print(dfSensor.shape)
    dfSensor.set_index("datetime", inplace=True)
    dfSensor = dfSensor.reindex(full_index)
    dfSensor["sm_value"] = dfSensor["sm_value"].interpolate()
    print(dfSensor.shape)
    sensors[i] = dfSensor
    print('-'*10)

(3619, 2)
(3635, 1)
----------
(3563, 2)
(3635, 1)
----------
(3619, 2)
(3635, 1)
----------
(3599, 2)
(3635, 1)
----------
(3556, 2)
(3635, 1)
----------
(3556, 2)
(3635, 1)
----------
(3556, 2)
(3635, 1)
----------
(3556, 2)
(3635, 1)
----------
(3556, 2)
(3635, 1)
----------
(3556, 2)
(3635, 1)
----------
(3556, 2)
(3635, 1)
----------
(3556, 2)
(3635, 1)
----------

## Meteo

In [7]:
dfMeteo = pd.read_csv('open-meteo.csv')
dfMeteo["datetime"] = pd.to_datetime(dfMeteo["datetime"])

dfMeteo.set_index("datetime", inplace=True)
dfMeteo = dfMeteo.reindex(full_index)
print(dfMeteo.index.min())
print(dfMeteo.index.max())
print(dfMeteo.shape)

2024-12-12 12:00:00
2025-05-12 22:00:00
(3635, 11)

## Set meteo station

In [8]:
dfMeteoStation = pd.read_excel('WeatherStation.xlsx', usecols=[1,2,3,4,5,6,7,8,9])
print(dfMeteoStation)
dfMeteoStation["datetime"] = dfMeteoStation["datetime"].dt.round('h')
dfMeteoStation_rev = dfMeteoStation.groupby('datetime').mean()
print(dfMeteoStation_rev.index.min())
print(dfMeteoStation_rev.index.max())
print(dfMeteoStation_rev)

                datetime  Temp  Hum    Int  UVI  WS   WD  RG      BP
0    2024-11-03 10:01:23    27   45   2076    0   0  164   0   98440
1    2024-11-03 10:06:26    27   44   2117    0   0  164   0   98440
2    2024-11-03 10:11:28    27   43   2145    0   0  164   0   98440
3    2024-11-03 10:16:30    27   42   2120    0   0  164   0   98440
4    2024-11-03 10:21:32    27   40   2344    0   0  164   0   98430
...                  ...   ...  ...    ...  ...  ..  ...  ..     ...
5914 2025-05-15 08:53:42    16   74  22732    1   3  264   0  100540
5915 2025-05-15 09:54:08    18   66  27588    2   2  272   0  100580
5916 2025-05-15 10:54:33    20   54  80029    5   4  268   0  100610
5917 2025-05-15 11:54:58    21   49  98760    7   4  240   0  100600
5918 2025-05-15 12:55:24    22   47  42304    4   5  271   0  100580

[5919 rows x 9 columns]
2024-11-03 10:00:00
2025-05-15 13:00:00
                          Temp        Hum           Int  UVI   WS     WD   RG  \
datetime
2024-11-03 10:00:00  27.000000  42.333333   2043.333333  0.0  0.0  164.0  0.0
2024-11-03 11:00:00  27.250000  36.583333   1688.833333  0.0  0.0  164.0  0.0
2024-11-03 12:00:00  27.833333  32.833333   1653.750000  0.0  0.0  164.0  0.0
2024-11-03 13:00:00  28.000000  32.333333   1499.083333  0.0  0.0  164.0  0.0
2024-11-03 14:00:00  28.000000  32.583333   1317.250000  0.0  0.0  164.0  0.0
...                        ...        ...           ...  ...  ...    ...  ...
2025-05-15 09:00:00  16.000000  74.000000  22732.000000  1.0  3.0  264.0  0.0
2025-05-15 10:00:00  18.000000  66.000000  27588.000000  2.0  2.0  272.0  0.0
2025-05-15 11:00:00  20.000000  54.000000  80029.000000  5.0  4.0  268.0  0.0
2025-05-15 12:00:00  21.000000  49.000000  98760.000000  7.0  4.0  240.0  0.0
2025-05-15 13:00:00  22.000000  47.000000  42304.000000  4.0  5.0  271.0  0.0

                                BP
datetime
2024-11-03 10:00:00   98435.000000
2024-11-03 11:00:00   98426.666667
2024-11-03 12:00:00   98415.000000
2024-11-03 13:00:00   98382.500000
2024-11-03 14:00:00   98346.666667
...                            ...
2025-05-15 09:00:00  100540.000000
2025-05-15 10:00:00  100580.000000
2025-05-15 11:00:00  100610.000000
2025-05-15 12:00:00  100600.000000
2025-05-15 13:00:00  100580.000000

[4181 rows x 8 columns]

In [9]:
dfMeteoStation_rev = dfMeteoStation_rev.reindex(full_index)
print(dfMeteoStation_rev.index.min())
print(dfMeteoStation_rev.index.max())
print(dfMeteoStation_rev.shape)

2024-12-12 12:00:00
2025-05-12 22:00:00
(3635, 8)

In [11]:
dfMeteoStation_rev.columns

Index(['Temp', 'Hum', 'Int', 'UVI', 'WS', 'WD', 'RG', 'BP'], dtype='object')

In [12]:
dfMeteoStation_rev[['Temp', 'Hum', 'Int', 'UVI', 'WS', 'WD', 'RG', 'BP']] = dfMeteoStation_rev[['Temp', 'Hum', 'Int', 'UVI', 'WS', 'WD', 'RG', 'BP']].interpolate()
dfMeteoStation_rev.shape

(3635, 8)

In [13]:
dfMeteoStation_rev

                     Temp   Hum      Int  UVI   WS     WD   RG        BP
2024-12-12 12:00:00  16.0  37.0  42135.0  3.0  2.0  316.0  0.0  100590.0
2024-12-12 13:00:00  18.0  34.0  45420.0  3.0  3.0  300.0  0.0  100500.0
2024-12-12 14:00:00  19.0  31.0  41185.0  3.0  3.0  324.0  0.0  100440.0
2024-12-12 15:00:00  19.0  38.0  28431.0  1.0  4.0   15.0  0.0  100380.0
2024-12-12 16:00:00  18.0  44.0  13915.0  1.0  2.0   54.0  0.0  100400.0
...                   ...   ...      ...  ...  ...    ...  ...       ...
2025-05-12 18:00:00  22.0  40.0  40912.0  2.0  4.0   30.0  0.0  100200.0
2025-05-12 19:00:00  21.0  41.0  11825.0  1.0  5.0   30.0  0.0  100190.0
2025-05-12 20:00:00  20.0  51.0   3264.0  0.0  3.0   42.0  0.0  100230.0
2025-05-12 21:00:00  18.0  59.0      0.0  0.0  0.0   76.0  0.0  100260.0
2025-05-12 22:00:00  18.0  55.0      0.0  0.0  2.0  138.0  0.0  100290.0

[3635 rows x 8 columns]

## LAI

In [16]:
dfLAI = pd.read_excel('LAI_Data.xlsx', sheet_name=f'Sheet1')
dfLAI["datetime"] = pd.to_datetime(dfLAI["datetime"]) + pd.to_timedelta("12:00:00")
dfLAI = dfLAI.set_index("datetime")
dfLAI = dfLAI.reindex(full_index)
print(dfLAI)

                     Sensor  Farmer
2024-12-12 12:00:00     NaN     NaN
2024-12-12 13:00:00     NaN     NaN
2024-12-12 14:00:00     NaN     NaN
2024-12-12 15:00:00     NaN     NaN
2024-12-12 16:00:00     NaN     NaN
...                     ...     ...
2025-05-12 18:00:00     NaN     NaN
2025-05-12 19:00:00     NaN     NaN
2025-05-12 20:00:00     NaN     NaN
2025-05-12 21:00:00     NaN     NaN
2025-05-12 22:00:00     NaN     NaN

[3635 rows x 2 columns]

In [18]:
values = {
    "Sensor": 0,
    "Farmer": 0,
}
dfLAI.loc["2024-12-12 12:00:00"] = values
dfLAI[['Sensor', 'Farmer']] = dfLAI[['Sensor', 'Farmer']].interpolate()
print(dfLAI)

                       Sensor    Farmer
2024-12-12 12:00:00  0.000000  0.000000
2024-12-12 13:00:00  0.000088  0.000183
2024-12-12 14:00:00  0.000175  0.000365
2024-12-12 15:00:00  0.000263  0.000548
2024-12-12 16:00:00  0.000351  0.000731
...                       ...       ...
2025-05-12 18:00:00  2.220000  1.760000
2025-05-12 19:00:00  2.220000  1.760000
2025-05-12 20:00:00  2.220000  1.760000
2025-05-12 21:00:00  2.220000  1.760000
2025-05-12 22:00:00  2.220000  1.760000

[3635 rows x 2 columns]

In [19]:
mapToSensor = {'Sensor': [3, 4, 7, 8, 11, 12],
               'Farmer': [1, 2, 5, 6, 9, 10]}

for i in range(1, 12+1):
    for k, v in mapToSensor.items():
        if i in v:
            dfLAI[f'{i}'] = dfLAI[k]

dfLAI.drop(['Sensor', 'Farmer'], axis=1, inplace=True)
print(dfLAI)

                            1         2         3         4         5  \
2024-12-12 12:00:00  0.000000  0.000000  0.000000  0.000000  0.000000
2024-12-12 13:00:00  0.000183  0.000183  0.000088  0.000088  0.000183
2024-12-12 14:00:00  0.000365  0.000365  0.000175  0.000175  0.000365
2024-12-12 15:00:00  0.000548  0.000548  0.000263  0.000263  0.000548
2024-12-12 16:00:00  0.000731  0.000731  0.000351  0.000351  0.000731
...                       ...       ...       ...       ...       ...
2025-05-12 18:00:00  1.760000  1.760000  2.220000  2.220000  1.760000
2025-05-12 19:00:00  1.760000  1.760000  2.220000  2.220000  1.760000
2025-05-12 20:00:00  1.760000  1.760000  2.220000  2.220000  1.760000
2025-05-12 21:00:00  1.760000  1.760000  2.220000  2.220000  1.760000
2025-05-12 22:00:00  1.760000  1.760000  2.220000  2.220000  1.760000

                            6         7         8         9        10  \
2024-12-12 12:00:00  0.000000  0.000000  0.000000  0.000000  0.000000
2024-12-12 13:00:00  0.000183  0.000088  0.000088  0.000183  0.000183
2024-12-12 14:00:00  0.000365  0.000175  0.000175  0.000365  0.000365
2024-12-12 15:00:00  0.000548  0.000263  0.000263  0.000548  0.000548
2024-12-12 16:00:00  0.000731  0.000351  0.000351  0.000731  0.000731
...                       ...       ...       ...       ...       ...
2025-05-12 18:00:00  1.760000  2.220000  2.220000  1.760000  1.760000
2025-05-12 19:00:00  1.760000  2.220000  2.220000  1.760000  1.760000
2025-05-12 20:00:00  1.760000  2.220000  2.220000  1.760000  1.760000
2025-05-12 21:00:00  1.760000  2.220000  2.220000  1.760000  1.760000
2025-05-12 22:00:00  1.760000  2.220000  2.220000  1.760000  1.760000

                           11        12
2024-12-12 12:00:00  0.000000  0.000000
2024-12-12 13:00:00  0.000088  0.000088
2024-12-12 14:00:00  0.000175  0.000175
2024-12-12 15:00:00  0.000263  0.000263
2024-12-12 16:00:00  0.000351  0.000351
...                       ...       ...
2025-05-12 18:00:00  2.220000  2.220000
2025-05-12 19:00:00  2.220000  2.220000
2025-05-12 20:00:00  2.220000  2.220000
2025-05-12 21:00:00  2.220000  2.220000
2025-05-12 22:00:00  2.220000  2.220000

[3635 rows x 12 columns]

# Irrigation

In [20]:

dfIRR = pd.DataFrame(columns=['f1','f2','f3','f4','f5','f6'], index=full_index)
dfIRR.fillna(0.0, inplace=True)

/var/folders/66/rpqcrym93h90yphhq7kgwhb00000gn/T/ipykernel_8715/2615553584.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dfIRR.fillna(0.0, inplace=True)

In [21]:
dfIRR.head()

                      f1   f2   f3   f4   f5   f6
2024-12-12 12:00:00  0.0  0.0  0.0  0.0  0.0  0.0
2024-12-12 13:00:00  0.0  0.0  0.0  0.0  0.0  0.0
2024-12-12 14:00:00  0.0  0.0  0.0  0.0  0.0  0.0
2024-12-12 15:00:00  0.0  0.0  0.0  0.0  0.0  0.0
2024-12-12 16:00:00  0.0  0.0  0.0  0.0  0.0  0.0

In [22]:
dfIrrigation = pd.read_excel('IrrigationEvents.xlsx', sheet_name='Irrigation')
dfIrrigation.rename(columns={"Date": "datetime", "Irrigation Volume": "volume"},
                     inplace=True)
dfIrrigation["datetime"] = pd.to_datetime(dfIrrigation["datetime"]) + pd.to_timedelta("12:00:00")
dfIrrigation.sort_values("datetime", ascending=True, inplace=True)
F = ['f1', 'f3', 'f5']
#S = ['f2', 'f4', 'f6']
dfIrrigation["Plot"] = dfIrrigation["Plot"].apply(
    lambda x: F if x == "Farmer" else [f"f{x}"]
)

In [23]:
dfIrrigation

              datetime          Plot     volume
7  2025-02-24 12:00:00          [f2]  18.260946
8  2025-02-24 12:00:00          [f4]  23.150877
9  2025-02-24 12:00:00          [f6]  21.931345
0  2025-03-04 12:00:00  [f1, f3, f5]  20.254153
1  2025-03-17 12:00:00  [f1, f3, f5]  18.967347
11 2025-03-17 12:00:00          [f4]  18.895500
10 2025-03-17 12:00:00          [f2]  24.480488
12 2025-03-19 12:00:00          [f6]  18.183007
15 2025-03-26 12:00:00          [f6]  24.940376
14 2025-03-26 12:00:00          [f4]  25.865908
13 2025-03-26 12:00:00          [f2]  42.181839
2  2025-03-28 12:00:00  [f1, f3, f5]  18.735255
3  2025-04-02 12:00:00  [f1, f3, f5]  18.933170
16 2025-04-02 12:00:00          [f2]  40.137729
17 2025-04-02 12:00:00          [f4]  27.818690
18 2025-04-02 12:00:00          [f6]  19.780989
19 2025-04-07 12:00:00          [f2]  39.174330
20 2025-04-07 12:00:00          [f4]  22.487494
21 2025-04-07 12:00:00          [f6]  18.476256
4  2025-04-11 12:00:00  [f1, f3, f5]  18.899979
24 2025-04-11 12:00:00          [f6]  17.058841
23 2025-04-11 12:00:00          [f4]  23.462647
22 2025-04-11 12:00:00          [f2]  36.248458
5  2025-04-18 12:00:00  [f1, f3, f5]  18.635782
26 2025-04-21 12:00:00          [f4]  18.487467
25 2025-04-21 12:00:00          [f2]  35.346237
27 2025-04-21 12:00:00          [f6]  18.661178
6  2025-04-22 12:00:00  [f1, f3, f5]  18.789576

In [25]:
dfIRR.head()

                      f1   f2   f3   f4   f5   f6
2024-12-12 12:00:00  0.0  0.0  0.0  0.0  0.0  0.0
2024-12-12 13:00:00  0.0  0.0  0.0  0.0  0.0  0.0
2024-12-12 14:00:00  0.0  0.0  0.0  0.0  0.0  0.0
2024-12-12 15:00:00  0.0  0.0  0.0  0.0  0.0  0.0
2024-12-12 16:00:00  0.0  0.0  0.0  0.0  0.0  0.0

In [31]:
for irr_ev in dfIrrigation.iterrows():
    #print(irr_ev[1]['Plot'])
    for p in irr_ev[1]['Plot']:
        dfIRR.loc[pd.to_datetime(irr_ev[1]['datetime']), p] = irr_ev[1]['volume']
        #print(dfIRR.loc[irr_ev[1]['datetime'], p])
        #pd.to_datetime(irr_ev[1]['datetime']),

In [24]:
#print(sensors[1].shape, sensors[1].columns)
print(dfIRR.shape, dfIRR.columns)
#print(dfMeteo.shape, dfMeteo.columns)

(3635, 6) Index(['f1', 'f2', 'f3', 'f4', 'f5', 'f6'], dtype='object')

In [27]:
sensors[1].head()

                      sm_value
2024-12-12 12:00:00  12.993426
2024-12-12 13:00:00  13.010599
2024-12-12 14:00:00  12.926013
2024-12-12 15:00:00  12.871484
2024-12-12 16:00:00  12.769203

In [32]:
meteo_fields = ['temperature_2m', 'relative_humidity_2m', 'cloud_cover',
       'wind_speed_10m', 'wind_direction_100m', 'soil_temperature_0_to_7cm',
       'soil_temperature_7_to_28cm', 'soil_temperature_28_to_100cm', 'rain',
       'precipitation', 'evapotranspiration']
meteo_station_fields = ['Temp', 'Hum', 'Int', 'UVI', 'WS', 'WD', 'RG', 'BP']

for i, field in enumerate(['f1', 'f2', 'f3', 'f4', 'f5', 'f6'], start=1):
    df_new = pd.DataFrame(columns=['s_a','s_b','irr','LAI','temperature_2m', 'relative_humidity_2m', 'cloud_cover',
       'wind_speed_10m', 'wind_direction_100m', 'soil_temperature_0_to_7cm',
       'soil_temperature_7_to_28cm', 'soil_temperature_28_to_100cm', 'rain',
       'precipitation', 'evapotranspiration'], index=full_index)
    df_new['irr'] = dfIRR[field]
    df_new['s_a'] = sensors[i*2]['sm_value']
    df_new['s_b'] = sensors[i*2-1]['sm_value']
    df_new['LAI'] = dfLAI[f'{i}']
    df_new[meteo_fields] = dfMeteo[meteo_fields]
    df_new[meteo_station_fields] = dfMeteoStation_rev[meteo_station_fields]
    df_new.to_csv(f'field_{field}',index_label='datetime')

In [29]:
df = pd.read_csv('field_f1')
df

,datetime,s_a,s_b,irr,LAI,temperature_2m,relative_humidity_2m,cloud_cover,wind_speed_10m,wind_direction_100m,...,precipitation,evapotranspiration,Temp,Hum,Int,UVI,WS,WD,RG,BP
0,2024-12-12 12:00:00,14.211700,12.993426,0.0,0.000000,18.1,35,0,6.4,311,...,0.0,0.31,16.0,37.0,42135.0,3.0,2.0,316.0,0.0,100590.0
1,2024-12-12 13:00:00,14.125555,13.010599,0.0,0.000183,18.9,34,0,7.1,334,...,0.0,0.32,18.0,34.0,45420.0,3.0,3.0,300.0,0.0,100500.0
2,2024-12-12 14:00:00,14.115591,12.926013,0.0,0.000365,18.9,33,1,7.0,351,...,0.0,0.29,19.0,31.0,41185.0,3.0,3.0,324.0,0.0,100440.0
3,2024-12-12 15:00:00,14.292916,12.871484,0.0,0.000548,17.8,41,1,9.6,40,...,0.0,0.23,19.0,38.0,28431.0,1.0,4.0,15.0,0.0,100380.0
4,2024-12-12 16:00:00,14.226170,12.769203,0.0,0.000731,15.9,50,0,8.4,74,...,0.0,0.13,18.0,44.0,13915.0,1.0,2.0,54.0,0.0,100400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3630,2025-05-12 18:00:00,21.292450,20.254208,0.0,1.760000,20.5,48,4,6.6,27,...,0.0,0.15,22.0,40.0,40912.0,2.0,4.0,30.0,0.0,100200.0
3631,2025-05-12 19:00:00,21.322579,20.479418,0.0,1.760000,18.4,59,11,2.6,53,...,0.0,0.03,21.0,41.0,11825.0,1.0,5.0,30.0,0.0,100190.0
3632,2025-05-12 20:00:00,21.492897,20.170613,0.0,1.760000,17.2,62,4,2.3,122,...,0.0,0.00,20.0,51.0,3264.0,0.0,3.0,42.0,0.0,100230.0
3633,2025-05-12 21:00:00,21.263699,20.311430,0.0,1.760000,16.2,63,54,4.1,183,...,0.0,0.01,18.0,59.0,0.0,0.0,0.0,76.0,0.0,100260.0
3634,2025-05-12 22:00:00,21.319845,20.188766,0.0,1.760000,15.2,63,86,4.0,193,...,0.0,0.01,18.0,55.0,0.0,0.0,2.0,138.0,0.0,100290.0

In [33]:
import plotly.graph_objects as go
import pandas as pd

fieldlist = [1,2,3,4,5,6]

# Create an empty figure
fig = go.Figure()

for i in fieldlist:
    df = pd.read_csv(f'field_f{i}')
    fig.add_trace(go.Scatter(
        x=df["datetime"],
        y=df["s_a"].to_list(),
        mode='lines',
        name=f"Field {i} in Line",
        visible='legendonly'
    ))
    fig.add_trace(go.Scatter(
        x=df["datetime"],
        y=df["s_b"].to_list(),
        mode='lines',
        name=f"Field {i} between Line",
        visible='legendonly'
    ))
    fig.add_trace(go.Scatter(
        x=df["datetime"],
        y=df["irr"].to_list(),
        mode='lines',
        name=f"Field {i} irrigation",
        visible='legendonly'
    ))
    fig.add_trace(go.Scatter(
        x=df["datetime"],
        y=df["LAI"].to_list(),
        mode='lines',
        name=f"Field {i} LAI",
        visible='legendonly'
    ))

fig.add_trace(go.Scatter(
    x=df["datetime"],
    y=df["RG"],
    mode='markers',
    marker=dict(
        size=5,
    ),
    name=f"rain Station"
))

fig.add_trace(go.Scatter(
    x=df["datetime"],
    y=df["rain"],
    mode='markers',
    marker=dict(
        size=5,
    ),
    name=f"rain Meteo"
))

fig.show()